### ISSUE TITLE
Using a json cache instead of object cache for better performance and efficiency

### ISSUE THREAD

**Issue by Luna-Klatzer** [Luna-Klatzer/openhiven.py#53]
**Issue:**
After the current implementation of marshmallow Object Validation, OpenHiven.py has shown that Object Creation and Instances create under masses heavy slowdowns and take up most of the initialisation time. Still, Validation is important to handle the data correctly and also check data. It might become unneeded in later versions, but currently, it seems like the best solution to remove unneeded code for checks. 

**Possible Solution:**
A possible solution is a small redesign of the overall way OpenHiven.py handles data. That means possibly using JSON-data caches which save instead of objects just their data in dictionary format. That can remove the needed time of creating instances at the startup and move the object creation when needed. A new validation method could provide a high-speed solution to the data issue by postponing the objects' need to when they are actually needed and making the validation faster.

This would mean replacing the current cache and storing only JSON-data and letting instances be only 'fancy interfaces to interact with the data'. This would also mean that instances would be created when objects are fetched, events are received, and the user needs to have objects to use. That means most of the time the cache will store only JSON-data. These instances would then also contain a `raw_data` field for accessing the JSON data. The properties would then only represent the JSON-data that fetch the data instead of storing data using unneeded variables. This way, data is changed, fetched and stored using dictionaries and methods will only return instances if the user expects it to return. This way, only barely instances need to be created, and the data can be stored without any decrease in performance.

**Additional Context:**
Implementing such a system would then automatically also require for the sake of speed the entire removal of the ready_state system that is currently in place, so it does not trigger events where the instances would then automatically need to be created. This means only after the Client actually started it will trigger an event and not see the initialisation messages as events to trigger. This way only after initialisation instances would be created in events speeding up the startup by a lot, but also changes of data where dictionary fields only need to be modified

**Comment by Nicolas-Klatzer** [comment]
@Nxybi Got anything to add OwO

**Comment by Nicolas-Klatzer** [comment]
Possible implementation using compiled schemas that are used inside the files of the type classes. These schemas would serve as example base for all OpenHiven.py dict-data types, which can be easily passed as **kwargs into `__init__`. Would then likely be implemented with #55 since data would then be validated through pure JSON.

**Comment by Nicolas-Klatzer** [comment]
**New Structure Plan for the Classes:**
- `types/*.py` classes will be objects to validate data and interact with the Hiven API:
   - `raw`: Raw Data that fetches the object itself
   - `form_object`: Function to validate data and transform it into the OpenHiven.py schema. If the object points to other objects it will only return standard ids instead of objects.
   - `from_dict`: Creates a new instance with functions to interact with the Hiven API. The data passed must be already validated using `form_object`
   - `validate`: Raw Validator that only checks if all data is present and usable!
   - `update`: Updates the raw data of the object
- `client/cache.py`: Class used for adding data to the cache. Will utilise form_object to validate the data and update it appropriately

**Comment by Luna-Klatzer** [comment]
Resolved with #65
